---
name: "JSONbin Action"
author: Yevhen Fabizhevskyi
description: "This action allows to generate custom HTTP responses using JSONbin service."
branding:
  icon: trash
  color: blue
inputs:
  api_key:
    description: "JSONbin API Key."
    required: true
  body:
    description: "Body to send in JSON format. In case you want to CREATE or UPDATE bin."
    required: false
    default: ""
  method:
    description: "Type of response that you want to send. Possible values are GET, CREATE, UPDATE, DELETE. Default is GET."
    required: false
    default: "GET"
  bin_id:
    description: "In case you want to UPDATE or DELETE bin."
    required: false
    default: ""
outputs:
  bin_id:
    description: "ID of a bin that has been created, updated or deleted."
    value: ${{ steps.jsonbin.outputs.bin_id }}
  url:
    description: "Access URL to a bin."
    value: ${{ steps.jsonbin.outputs.url }}
runs:
  using: "composite"
  steps:
    - name: Get JSONbin
      if: ${{ inputs.method == 'GET' }}
      id: get
      uses: fjogeleit/http-request-action@v1.16.3
      with:
        url: "https://api.jsonbin.io/v3/b/${{ inputs.bin_id }}"
        method: "GET"
        customHeaders: '{"X-Master-Key": "${{ inputs.api_key }}", "Accept": "application/json", "X-Bin-Meta": "true"}'
    - if: ${{ inputs.method == 'GET' }}
      run: |
        bin_id="${{ fromJson(steps.get.outputs.response).metadata.id }}"
        echo "JSONBIN_ACTION_BIN_ID=${bin_id}" >> "$GITHUB_ENV"
      shell: sh
    - name: Create JSONbin
      if: ${{ inputs.method == 'CREATE' }}
      id: create
      uses: fjogeleit/http-request-action@v1.16.3
      with:
        url: "https://api.jsonbin.io/v3/b"
        method: "POST"
        customHeaders: '{"X-Master-Key": "${{ inputs.api_key }}", "Accept": "application/json", "X-Bin-Private": "true"}'
        data: "${{ inputs.body }}"
    - if: ${{ inputs.method == 'CREATE' }}
      run: |
        bin_id="${{ fromJson(steps.create.outputs.response).metadata.id }}"
        echo "JSONBIN_ACTION_BIN_ID=${bin_id}" >> "$GITHUB_ENV"
      shell: sh
    - name: Update JSONbin
      if: ${{ inputs.method == 'UPDATE' }}
      id: update
      uses: fjogeleit/http-request-action@v1.16.3
      with:
        url: "https://api.jsonbin.io/v3/b/${{ inputs.bin_id }}"
        method: "PUT"
        customHeaders: '{"X-Master-Key": "${{ inputs.api_key }}", "Accept": "application/json", "X-Bin-Versioning": "false"}'
        data: "${{ inputs.body }}"
    - if: ${{ inputs.method == 'UPDATE' }}
      run: |
        bin_id="${{ fromJson(steps.update.outputs.response).metadata.parentId }}"
        echo "JSONBIN_ACTION_BIN_ID=${bin_id}" >> "$GITHUB_ENV"
      shell: sh
    - name: Delete JSONbin
      if: ${{ inputs.method == 'DELETE' }}
      id: delete
      uses: fjogeleit/http-request-action@v1.16.3
      with:
        url: "https://api.jsonbin.io/v3/b/${{ inputs.bin_id }}"
        method: "DELETE"
        customHeaders: '{"X-Master-Key": "${{ inputs.api_key }}"}'
    - if: ${{ inputs.method == 'DELETE' }}
      run: |
        bin_id="${{ fromJson(steps.delete.outputs.response).metadata.id }}"
        echo "JSONBIN_ACTION_BIN_ID=${bin_id}" >> "$GITHUB_ENV"
      shell: sh
    - name: Set output
      if: ${{ inputs.method == 'GET' || inputs.method == 'CREATE' || inputs.method == 'UPDATE' || inputs.method == 'DELETE' }}
      id: jsonbin
      run: |
        echo "bin_id=${JSONBIN_ACTION_BIN_ID}" >> "$GITHUB_OUTPUT"
        echo "url=https://api.jsonbin.io/v3/b/${JSONBIN_ACTION_BIN_ID}" >> "$GITHUB_OUTPUT"
      shell: sh
