---
name: "JSONbin Action"
author: Yevhen Fabizhevskyi
description: "This action allows to generate custom HTTP responses using JSONbin service."
branding:
  icon: trash
  color: blue
inputs:
  master-key:
    description: "JSONbin Master Key."
    required: true
  access-key:
    description: "JSONbin Access Key."
    required: true
  body:
    description: "Body to send in JSON format. In case you want to CREATE or UPDATE bin."
    required: false
    default: ""
  method:
    description: "Type of response that you want to send. Possible values are GET, CREATE, UPDATE, DELETE. Default is GET."
    required: false
    default: "GET"
  bin-id:
    description: "In case you want to UPDATE or DELETE bin."
    required: false
    default: ""
outputs:
  bin-id:
    description: "ID of a bin that has been created, updated or deleted."
    value: ${{ steps.jsonbin.outputs.bin-id }}
  url:
    description: "Access URL to a bin."
    value: ${{ steps.jsonbin.outputs.url }}
runs:
  using: "composite"
  steps:
    - name: Send JSONbin request
      if: ${{ contains(fromJSON('["GET", "CREATE", "UPDATE", "DELETE"]'), inputs.method) }}
      id: jsonbin
      env:
        INPUT_METHOD: "${{ inputs.method }}"
        INPUT_MASTER_KEY: "${{ inputs.master-key }}"
        INPUT_ACCESS_KEY: "${{ inputs.access-key }}"
        INPUT_BIN_ID: "${{ inputs.bin-id }}"
        INPUT_BODY: "${{ inputs.body }}"
      run: |
        bin_id=$(
          ${GITHUB_ACTION_PATH}/src/main.sh \
            "${INPUT_METHOD}" \
            "${INPUT_MASTER_KEY}" \
            "${INPUT_ACCESS_KEY}" \
            "${INPUT_BIN_ID}" \
            "${INPUT_BODY}"
        )
        echo "bin-id=${bin_id}" >> "$GITHUB_OUTPUT"
        echo "url=https://api.jsonbin.io/v3/b/${bin_id}" >> "$GITHUB_OUTPUT"
      shell: sh
    - name: Fail
      if: ${{ !contains(fromJSON('["GET", "CREATE", "UPDATE", "DELETE"]'), inputs.method) }}
      env:
        INPUT_METHOD: "${{ inputs.method }}"
      run: |
        message="${INPUT_METHOD} method is not supported. Allowed values: GET, CREATE, UPDATE, DELETE"
        echo "::error title=Method is not supported::{message}"
        exit 1
      shell: sh
