---
name: Create release

on:
  push:
    branches:
      - 'feature/**'
      - 'bump/**'

jobs:
  create_release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Get commits since last release
        id: changes
        uses: simbo/changes-since-last-release-action@v1
      - run: echo "${{ steps.changes.outputs.last-tag }}"
      - name: Get latest version
        uses: bhowell2/github-substring-action@v1.0.0
        id: version
        with:
          value: ${{ steps.changes.outputs.last-tag }}
          length_from_end: 1
      - run: echo "${{ steps.version.outputs.substring }}"
      - name: Increase version
        id: semver
        uses: matt-FFFFFF/simple-semver@v0.1.0
        with:
          semver-input: ${{ steps.version.outputs.substring }}
          increment: p
      - run: echo "${{ steps.semver.outputs.semver }}"
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.semver.outputs.semver }}
          release_name: v${{ steps.semver.outputs.semver }}
          body: |
            # Changes
            ${{ steps.changes.outputs.log }}
          draft: false
          prerelease: false
