---
name: Functional Tests

on: # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - .github/workflows/functional-tests.yml
      - action.yml
  push:
    branches:
      - main
  schedule:
    # Every Friday at 09:00 JST
    - cron: "0 0 * * 5"
  workflow_dispatch:
    inputs:
      log-level:
        description: "Log level:"
        required: false
        default: "info"
        type: choice
        options: [debug, info, warning, error]

jobs:
  functional-tests:
    name: Test JSONbin
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Prepare GET headers
        id: http-req
        run: |
          headers=$(
            jq -cn \
              --arg mk '${{ secrets.JSONBIN_MASTER_KEY }}' \
              --arg ak '${{ secrets.JSONBIN_ACCESS_KEY }}' \
              '{"X-Master-Key": $mk, "X-Access-Key": $ak, "X-Bin-Meta": "true", "Accept": "application/json"}'
          )
          echo "headers=${headers}" >> "$GITHUB_OUTPUT"
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v7
        with:
          persist-credentials: "false"
      - name: Create bin
        uses: ./
        id: jsonbin-create
        with:
          body: '{"running_by":"${{ github.actor }}"}'
          method: "CREATE"
          master-key: "${{ secrets.JSONBIN_MASTER_KEY }}"
          access-key: "${{ secrets.JSONBIN_ACCESS_KEY }}"
          log-level: "${{ github.event.inputs.log-level || 'info' }}"
      - name: Validate output
        env:
          STEP_JSONBIN_CREATE_OUTPUT_BIN_ID: "${{ steps.jsonbin-create.outputs.bin-id }}"
          STEP_JSONBIN_CREATE_OUTPUT_URL: "${{ steps.jsonbin-create.outputs.url }}"
        run: |
          [[ "${#STEP_JSONBIN_CREATE_OUTPUT_BIN_ID}" -eq 0 ]] && exit 1;
          [[ "${STEP_JSONBIN_CREATE_OUTPUT_URL}" == "https://api.jsonbin.io/v3/b/${STEP_JSONBIN_CREATE_OUTPUT_BIN_ID}" ]] || exit 1;
      - name: Call URL that was returned
        uses: fjogeleit/http-request-action@f98bb26551cd1af7d3eb2674578a80754ece88db # v2.0.1
        id: http1
        with:
          url: "${{ steps.jsonbin-create.outputs.url }}"
          method: "GET"
          customHeaders: "${{ steps.http-req.outputs.headers }}"
      - name: Validate response
        env:
          STEP_HTTP1_OUTPUT_RESPONSE: "${{ steps.http1.outputs.response }}"
        run: |
          [[ "$(jq -c '.record' <<< "${STEP_HTTP1_OUTPUT_RESPONSE}")" == "{\"running_by\":\"${GITHUB_ACTOR}\"}" ]] || exit 1;
      - name: Get bin
        uses: ./
        id: jsonbin-get
        with:
          bin-id: "${{ steps.jsonbin-create.outputs.bin-id }}"
          method: "GET"
          master-key: "${{ secrets.JSONBIN_MASTER_KEY }}"
          access-key: "${{ secrets.JSONBIN_ACCESS_KEY }}"
          log-level: "${{ github.event.inputs.log-level || 'info' }}"
      - name: Validate output
        env:
          STEP_JSONBIN_GET_OUTPUT_BIN_ID: "${{ steps.jsonbin-get.outputs.bin-id }}"
          STEP_JSONBIN_GET_OUTPUT_URL: "${{ steps.jsonbin-get.outputs.url }}"
        run: |
          [[ "${#STEP_JSONBIN_GET_OUTPUT_BIN_ID}" -eq 0 ]] && exit 1;
          [[ "${STEP_JSONBIN_GET_OUTPUT_URL}" == "https://api.jsonbin.io/v3/b/${STEP_JSONBIN_GET_OUTPUT_BIN_ID}" ]] || exit 1;
      - name: Call URL that was returned
        uses: fjogeleit/http-request-action@f98bb26551cd1af7d3eb2674578a80754ece88db # v2.0.1
        id: http2
        with:
          url: "${{ steps.jsonbin-get.outputs.url }}"
          method: "GET"
          customHeaders: "${{ steps.http-req.outputs.headers }}"
      - name: Validate response
        env:
          STEP_HTTP2_OUTPUT_RESPONSE: "${{ steps.http2.outputs.response }}"
        run: |
          [[ "$(jq -c '.record' <<< "${STEP_HTTP2_OUTPUT_RESPONSE}")" == "{\"running_by\":\"${GITHUB_ACTOR}\"}" ]] || exit 1;
      - name: Update bin
        uses: ./
        id: jsonbin-update
        with:
          body: '{"author":"${{ github.actor }}"}'
          method: "UPDATE"
          bin-id: "${{ steps.jsonbin-create.outputs.bin-id }}"
          master-key: "${{ secrets.JSONBIN_MASTER_KEY }}"
          access-key: "${{ secrets.JSONBIN_ACCESS_KEY }}"
          log-level: "${{ github.event.inputs.log-level || 'info' }}"
      - name: Call URL that was returned
        uses: fjogeleit/http-request-action@f98bb26551cd1af7d3eb2674578a80754ece88db # v2.0.1
        id: http3
        with:
          url: "${{ steps.jsonbin-update.outputs.url }}"
          method: "GET"
          customHeaders: "${{ steps.http-req.outputs.headers }}"
      - name: Validate response
        env:
          STEP_HTTP3_OUTPUT_RESPONSE: "${{ steps.http3.outputs.response }}"
        run: |
          [[ "$(jq -c '.record' <<< "${STEP_HTTP3_OUTPUT_RESPONSE}")" == "{\"author\":\"${GITHUB_ACTOR}\"}" ]] || exit 1;
      - name: Delete bin
        uses: ./
        id: jsonbin-delete
        with:
          bin-id: "${{ steps.jsonbin-update.outputs.bin-id }}"
          method: "DELETE"
          master-key: "${{ secrets.JSONBIN_MASTER_KEY }}"
          access-key: "${{ secrets.JSONBIN_ACCESS_KEY }}"
          log-level: "${{ github.event.inputs.log-level || 'info' }}"
      - name: Validate URL does not exist
        env:
          STEP_JSONBIN_UPDATE_OUTPUT_URL: "${{ steps.jsonbin-update.outputs.url }}"
        run: |
          [[ $(curl -s -o /dev/null -w "%{http_code}" "${STEP_JSONBIN_UPDATE_OUTPUT_URL}") -eq 404 ]] || exit 1;
