---
name: Sync Labels

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - dependabot/github_actions/fjogeleit/http-request-action-1.16.0
  workflow_dispatch: {}

jobs:
  sync-labels:
    name: Labels
    uses: fabasoad/reusable-workflows/.github/workflows/wf-sync-labels.yml@fix/sync-labels
    secrets: inherit # pragma: allowlist secret
