---
name: Unit Tests

on:
  push:
    branches:
      - 'main'
      - 'fix-*'
      - 'dependabot/**'
      - 'feature-*'

jobs:
  unit_tests:
    name: Lint and Test
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        id: cache
        uses: actions/cache@v2.1.7
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Compile
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: yarn install --ignore-scripts
      - name: Lint
        run: yarn run lint
      - name: Unit tests
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: yarn test
        if: github.ref != 'refs/heads/main'
      - name: Unit tests with coverage
        uses: paambaati/codeclimate-action@v3.0.0
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          API_KEY: ${{ secrets.API_KEY }}
        with:
          coverageCommand: yarn test
          debug: true
